// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rapqgykcxxggyvnkvuiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcHFneWtjeHhnZ3l2bmt2dWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDA1NjgsImV4cCI6MjA1OTU3NjU2OH0.S88Ll4Kb4U0kgomi3EveZ4DUmL4KGddrUmFuqUsFKTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);